name: Publish to npm
on:
  release:
    types: [published] # Se déclenche uniquement quand vous publiez une "Release" sur GitHub
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # CRUCIAL : C'est ce qui active OpenID Connect (OIDC) sans mot de passe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Publish to npm with Provenance
        run: npm publish --provenance --access public
